### ISSUE TITLE
Plugins section in `libs.versions.toml` is moved to the top by `refreshVersions`

### ISSUE THREAD

**Issue by joffrey-bion** [Splitties/refreshVersions#690]
## 🐛 Describe the bug

Not a real bug per se, but an annoyance. The order of the sections in the generated `libs.versions.toml` is unusual (`plugins` comes first, before `versions`).

It would be better if `plugins` were at the bottom for the following reasons:

* the `versions` section is the thing that we update the most, and manually, so it's nice if it's easier to access - at the top
* `plugins` usually reference version numbers from the `version` section, so it's more natural for it to appear before
* the [official example](https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format) shows the sections in this order: `versions`, `libraries`, `bundles`, `plugins`

## ⚠️ Current behavior

The `plugins` section is moved to the top.

## ✅ Expected behavior

The `plugins` section stays wherever it is, or is moved to the bottom.

## 💣 Steps to reproduce

Create a `libs.versions.toml` with a `plugins` section. For instance:

```toml
[versions]

spring-boot = "3.1.1"

[plugins]

spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
```

Then run `refreshVersions` and notice that the `plugins` section moved.
